AWSTemplateFormatVersion: '2010-09-09'
Description: 'Archivo 3 - Alta Disponibilidad 100% Automática'

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'

  StudentPrefix:
    Type: String
    Default: Kevin-Arley

Resources:
  # El ALB requiere zonas de disponibilidad. Si no se especifican, AWS asume por defecto la red de la cuenta.
  ApplicationLoadBalancer:
    Type: AWS::EC2::ALB
    Properties:
      Name: !Sub "ALB-${StudentPrefix}"
      Scheme: internet-facing
      Type: application
      # Truco: Al no pasarle subredes fijas, AWS asocia el ALB a las subredes por defecto de la Región
      SecurityGroups:
        - !ImportValue 
          Name: !Sub "${StudentPrefix}-ALBSecurityGroupId"
      Tags:
        - Key: Name
          Value: !Sub "ALB-${StudentPrefix}"

ALBTargetGroup:
    Type: AWS::AutoScaling::TargetGroup
    Properties:
      Name: !Sub "TG-${StudentPrefix}"
      HealthCheckProtocol: HTTP
      HealthCheckPort: '80'
      HealthCheckPath: /index.html
      IntervalSeconds: 30
      Protocol: HTTP
      Port: 80
      VpcId: !ImportValue 
        Name: !Sub "${StudentPrefix}-VpcId"
      TargetType: instance

  ALBListener:
    Type: AWS::EC2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  InstanceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "LaunchTemplate-${StudentPrefix}"
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: !Ref LatestAmiId
        SecurityGroupIds:
          - !ImportValue 
            Name: !Sub "${StudentPrefix}-EC2SecurityGroupId"
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install httpd -y
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Examen Final Cloud Computing - Instancia del Auto Scaling Group de ${StudentPrefix}</h1>" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "ALB-ASG-${StudentPrefix}"
      LaunchTemplate:
        LaunchTemplateId: !Ref InstanceLaunchTemplate
        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      Tags:
        - Key: Name
          Value: !Sub "ASG-Instance-${StudentPrefix}"
          PropagateAtLaunch: true

  AsgWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PoolState: Stopped
      MinSize: 1

Outputs:
  AsgName:
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub "${StudentPrefix}-AsgName"

  LaunchTemplateId:
    Value: !Ref InstanceLaunchTemplate
    Export:
      Name: !Sub "${StudentPrefix}-LaunchTemplateId"
