AWSTemplateFormatVersion: '2010-09-09'
Description: 'Archivo 1 - Capa de Seguridad Automatizada'

Parameters:
  StudentPrefix:
    Type: String
    Default: Kevin-Arley

Resources:
  # Esto busca la VPC por defecto de tu compañero en automático directamente en AWS
  DefaultVpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Security Group para el ALB de ${StudentPrefix}"
      VpcId: !Ref DefaultVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "SecurityGroups-${StudentPrefix}-ALB"

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "Security Group para servidores EC2 de ${StudentPrefix}"
      VpcId: !Ref DefaultVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "SecurityGroups-${StudentPrefix}-EC2"

Outputs:
  ExportALBSGId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${StudentPrefix}-ALBSecurityGroupId"

  ExportEC2SGId:
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub "${StudentPrefix}-EC2SecurityGroupId"

  ExportVpcId:
    Value: !Ref DefaultVpc
    Export:
      Name: !Sub "${StudentPrefix}-VpcId"
