name: AWS Infrastructure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Stacks to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Stack 1: Seguridad
      - name: Deploy Security Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: SecurityGroups-Stack
          template: templates/security.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "StudentPrefix=Kevin-Arley"

      # Stack 2: EC2 Estática
      - name: Deploy EC2 Static Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: EC2Static-Stack
          template: templates/ec2.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "StudentPrefix=Kevin-Arley"

      # Stack 3: Alta Disponibilidad (ALB y ASG)
      - name: Deploy ALB & ASG Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ALB-ASG-Stack
          template: templates/alb-asg.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "StudentPrefix=Kevin-Arley"

      # Stack 4: Automatización
      - name: Deploy Automation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Automation-Stack
          template: templates/automation.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "StudentPrefix=Kevin-Arley"